name: prague
version: "0.1.0"
config-version: 2
profile: prague

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  prague:
    staging:
      +schema: silver
      +materialized: view
    marts:
      +schema: gold
      +materialized: table

snapshots:
  prague:
    +target_schema: snapshots

seeds:
  prague:
    +schema: seeds
